### ISSUE TITLE
New error with dart 2.12

### ISSUE THREAD

**Issue by drpond1** [petitparser/dart-petitparser#103]
I have been using your xml package to easily parse an xml file.    But after upgrading my project to 2.12 with the latest xml software I get  a typing error,  at the beginning of the translation
throwing an exception up to my code.

At my code: var doc = xml.XmlDocument.parse(input);
to  the XML parser
    final parser = documentParserCache[mapping];
eventually to petit parser
   _resolve(Reference(start ?? this.start, arguments)) as Parser<T>;
and then  eventually to an exception on equal check

other.function  is a   f  bound document  ()    tested against function

in reference.dart at line 19:

 bool operator ==(Object other) {
    if (other is Reference) {
      if (other.function != function ||

{}other.function._equals is not a function
TypeError: other.function._equals is not a function
    at reference$.Reference.new._equals (http://localhost:53322/packages/petitparser/src/definition/grammar.sound.ddc.js:81:29)
    at Object.equals (http://localhost:53322/packages/build_web_compilers/src/dev_compiler/dart_sdk.sound.js:5074:47)
    at LinkedMap.new._get (http://localhost:53322/packages/build_web_compilers/src/dev_compiler/dart_sdk.sound.js:21993:24)
    at _dereference (http://localhost:53322/packages/petitparser/src/definition/grammar.sound.ddc.js:177:36)
    at parser$.XmlParserDefinition.new.[_resolve] (http://localhost:53322/packages/petitparser/src/definition/grammar.sound.ddc.js:208:30)
    at parser$.XmlParserDefinition.new.build (http://localhost:53322/packages/petitparser/src/definition/grammar.sound.ddc.js:172:49)
    at XmlCache.new.<anonymous> (http://localhost:53322/packages/xml/src/xml/entities/default_mapping.sound.ddc.js:2309:174)
    at XmlCache.new._get (http://localhost:53322/packages/xml/src/xml/entities/default_mapping.sound.ddc.js:1915:52)
    at Function.parse (http://localhost:53322/packages/xml/src/xml/entities/default_mapping.sound.ddc.js:2242:49)
    at Object.translateXML (http://localhost:53322/drpond.sound.ddc.js:39699:38)
    at http://localhost:53322/drpond.sound.ddc.js:38502:22
    at Object._checkAndCall (http://localhost:53322/packages/build_web_compilers/src/dev_compiler/dart_sdk.sound.js:4869:16)
    at Object.dcall (http://localhost:53322/packages/build_web_compilers/src/dev_compiler/dart_sdk.sound.js:4874:17)
    at FileReader.<anonymous> (http://localhost:53322/packages/build_web_compilers/src/dev_compiler/dart_sdk.sound.js:97033:100)

**Comment by renggli** [comment]
I encountered that problem a couple of days ago as well and reported it here: https://github.com/dart-lang/webdev/issues/1291. The workaround I found was to use a `--release` build, instead of the `--debug` build.

Please follow up on the mentioned bug, to show that this is not only me that is affected 😉

**Comment by dnfield** [comment]
This is almost certainly caused by https://github.com/dart-lang/sdk/issues/45762 - there's some bug in DDC. flutter_svg is also suffering from this problem fr the same reasons.

**Comment by dnfield** [comment]
This has been fixed in Dart and will be cherry picked into the current Dart beta for the next Dart stable. It should also be fixed in the next Flutter stable release.

**Comment by renggli** [comment]
I can no longer reproduce the problem with the latest dev version of Dart (2.14.0-32.0.dev (dev) (Thu Apr 22 20:17:19 2021 -0700) on "macos_x64"). Thank you!
